### ISSUE TITLE
Run away algorithm and detecting enemy distance

### ISSUE THREAD

**Issue by kadorek** [HeRoBaNd/Toshinou-Buttman-Gagong#1]
first of all i appreciate your work. i suggest and improvment at "run away from enemy" algorithm such as the nearst gate can be closer to enemy than the player ship. so the algorthm must find the nearst gate that is far from enemy. i think. 

Like : 

to api.js  ; 

findNearestGateForRunAway(enemey){
    var minDist = 100000;
    var finalGate;
    this.gates.forEach(gate => {
      var enemeyDistance=enemy.distanceTo(gate.position);
      var dist = window.hero.distanceTo(gate.position);
      if (enemeyDistance<dist) {
        continue;
      }
      if (dist < minDist) {
        finalGate = gate;
        minDist = dist;
      }
    });

    return {gate: finalGate, distance: minDist}; 
  }

CheckForEnemy() {
        var result={run:false,enemy:null,edist:100000};
        var enemyDistance = 100000;
        var enemyShip;
        var kac = false;
        for (var property in this.ships) {
            var ship = this.ships[property];
            ship.update();
            if (!ship.isNpc && ship.isEnemy) {
                var dist = ship.distanceTo(window.hero.position);
                if (enemyDistance > dist) {
                    enemyDistance = dist;
                    result.edist=dist;
                    result.enemy=ship;
                }
            }
        }
        if (enemyDistance<2000) { // 2000 run away detect distance
            result.run=true;
            return result;
        }
        return result;
    }

to worker.js;

var enemyresult=api.CheckForEnemy();
    if (enemyresult.run) {
      console.log("runaway ");
        let gate = api.findNearestGateForRunAway(enemyresult.enemy);
        if (gate.gate) {
            let x = gate.gate.position.x;
            let y = gate.gate.position.y;
            api.isRepairing = true;
            api.move(x, y);
            window.movementDone = false;
            return;
        }
    }

have a good programming.

**Comment by HeRoBaNd** [comment]
Ty for answer :3 We are will try!
