### ISSUE TITLE
Collecting box when circling around npcs

### ISSUE THREAD

**Issue by kadorek** [HeRoBaNd/Toshinou-Buttman-Gagong#2]
Hi,

I have adjusted your code in worker.js and add some stuff to collecting box when circle around npc. And i want to add it.

**Comment by HeRoBaNd** [comment]
Hi,

You can add Pull request and im add it.

**Comment by kadorek** [comment]
i am not good at using github can u explain how can i do pull req.

**Comment by HeRoBaNd** [comment]
Added!
