### ISSUE TITLE
Using ship abilities

### ISSUE THREAD

**Issue by kadorek** [HeRoBaNd/Toshinou-Buttman-Gagong#3]
Hi,

As everyone know some ships has unique abilities. For using thees abilities the callback function must be added to swf. May be callback function can be added for hooking keyboard event. What about this idea.

**Comment by HeRoBaNd** [comment]
Yes, for this we need to add callbacks in main.swf. But ATM - we dont know how :D
And... We need much more callbacks in main.swf:
Like PET, Abilities, JumpGateFunction and more and more...

**Comment by kadorek** [comment]
i will inspect the swf and if i found it i will inform u
